/**
 * @readonly
 * @enum
 */
const ERROR_CODE = {
  AUTHERR: 'AUTHORIZATION_ERROR',
  NOAUTHERR: 'MISSING_AUTHORIZATION',
  INVLDAUTHTOKEN: 'INVALID_AUTH_TOKEN',
  INACTIVEACCT: 'INACTIVE_ACCOUNT',
  EXPIREDTOKEN: 'EXPIRED_TOKEN',
  INVLDREQ: 'INVALID_REQUEST',
  PERMERR: 'PERMISSION_ERROR',
  LIMITERR: 'LIMIT_ERROR',
  FEEERR: 'FEE_ERROR',
  NOTFOUND: 'RESOURCE_NOT_FOUND',
  APPERR: 'APPLICATION_ERROR',
  HTTPREQERR: 'INTERNAL_REQ_ERROR',
  DUPLRCRD: 'DUPLICATE_RECORD',
  VALIDATIONERR: 'VALIDATION_ERROR',
  INVLDDATA: 'INVALID_REQUEST_DATA',
  RTLIMERR: 'RATE_LIMIT_ERROR',
  SL02: 'SLUG_TAKEN',
  AC01: 'ACCESS_CODE_REQUIRED',
  AC05: 'ACCESS_CODE_NOT_ALLOWED',
  NF01: 'CARD_NOT_FOUND',
  NF02: 'CARD_IS_DRAFT',
  AC03: 'CARD_IS_PRIVATE',
  AC04: 'INVALID_ACCESS_CODE',
  DUP01: 'DUPLICATE_ACCESS_CODE',
};

const ERROR_STATUS_CODE_MAPPING = {
  AUTHORIZATION_ERROR: 401,
  MISSING_AUTHORIZATION: 401,
  INVALID_AUTH_TOKEN: 401,
  INACTIVE_ACCOUNT: 401,
  EXPIRED_TOKEN: 401,
  PERMISSION_ERROR: 401,
  INVALID_REQUEST: 403,
  LIMIT_ERROR: 403,
  FEE_ERROR: 403,
  RESOURCE_NOT_FOUND: 404,
  DUPLICATE_RECORD: 409,
  APPLICATION_ERROR: 500,
  RATE_LIMIT_ERROR: 429,
  SLUG_TAKEN: 400,
  ACCESS_CODE_REQUIRED: 400,
  ACCESS_CODE_NOT_ALLOWED: 400,
  CARD_NOT_FOUND: 404,
  CARD_IS_DRAFT: 404,
  CARD_IS_PRIVATE: 403,
  INVALID_ACCESS_CODE: 403,
  DUPLICATE_ACCESS_CODE: 400,
};

module.exports = { ERROR_CODE, ERROR_STATUS_CODE_MAPPING };
